.PHONY: all
all: XXX.pdf

FILES+=		XXX.tex aims.tex abstract.tex XXX.bib

XXX.pdf: ${FILES}
XXX.pdf: llncs biblatex-lncs


### INCLUDES ###

INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
